#!/bin/bash


list-ecr-repos(){
	
	aws ecr describe-repositories \
		--query "
      	repositories[].[
        repositoryName,
        registryId,
        repositoryUri
        ]"                        \
        --output text
}