#!/bin/bash

CREDENTIALS="$1"


export_credentials() {
	echo "exporting credentials!!"
	local access_key_id
	local access_secret_key
	local default_region

	access_key_id=$(grep -w "AWS_ACCESS_KEY_ID" "${CREDENTIALS}" | sed "s/.*=//g")
	access_secret_key=$(grep -w "AWS_ACCESS_KEY_ID" "${CREDENTIALS}" | sed "s/.*=//g")
    default_region=$(grep -w "AWS_REGION" "${CREDENTIALS}" | sed "s/.*=//g")

    echo "Fetched access_key_id: ${access_key_id}"

	if  [[ ! -z  "${access_key_id}" && ! -z "${access_secret_key}" && ! -z "${default_region}" ]]; then
		export AWS_ACCESS_KEY_ID="${access_key_id}"
		export AWS_SECRET_ACCESS_KEY="${access_secret_key}"
		export AWS_DEFAULT_REGION="${default_region}"
		return 0
	else 
		echo_stderr "An error occured while fetching credentials!"
		return 1

	fi
	
	return

}

