#!/bin/bash

CREDENTIAL_FILE=$1


export_variable() {
	local access_key_id=$(egrep -w "AWS_ACCESS_KEY_ID" $CREDENTIAL_FILE | sed "s/.*=//g")
	local access_secret_key=$(egrep -w "AWS_ACCESS_KEY_ID" $CREDENTIAL_FILE | sed "s/.*=//g")
	local default_region=$(egrep -w "AWS_REGION" $CREDENTIAL_FILE | sed "s/.*=//g")

	if  [[ ! -z  "$access_key_id" && ! -z "$access_secret_key" && ! -z "$default_region" ]]; then
		export AWS_ACCESS_KEY_ID="$access_key_id"
		export AWS_SECRET_ACCESS_KEY="$access_secret_key"
		export AWS_DEFAULT_REGION="$default_region"
	else 
		echo "An error occured while fetching credentials!"
		exit 1

	fi
	
	return

}

