#!/bin/bash

CREDENTIAL_FILE=$1

validate_file() {
	echo "#####################"
	echo "Checking if file exists!"
	echo "#####################"


	if [[ -f "$CREDENTIAL_FILE" ]]; then
		echo "File exists! Initialize credential variables"
		auth=$(export_auth "$CREDENTIAL_FILE")
		if [[ $auth == "true" ]]; then
			echo "auth exported successfully!"
			return 0
		else
			echo "An error occured while fetching auth!"
			return 1
		fi

	else 
		echo "File path provided does not exist!"
		return 1
	fi

	return
}

