#!/bin/bash

# List IAM Users
#

# $ iam-users
iam-users() {

	aws iam list-users    \
    	--output text       \
    	--query '
      	Users[].[
        UserName,
        UserId,
        CreateDate
    	]'
 }

