#!/bin/bash

show_usage() {
	  
	 echo_stderr "Usage: $0 [--credentials=<path>] \
	 					 $0 [--help]\n \
	 					 $ list-iam-users\n \
	 					 $ list-ec2-instances\n \
	 					 $ list-s3-buckets\n \
	 					 $ list-rds-instances\n \
	 					 $ list-ecs-clusters\n \
	 					 $ list-ecr-repositories"

}